# Generated by Django 5.2.6 on 2025-11-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="cooking_time",
            field=models.PositiveIntegerField(default=0, help_text="زمان پخت به دقیقه"),
        ),
        migrations.AddField(
            model_name="order",
            name="cooking_start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
